site_name: Vanessa Eaton Personal Site
nav:
  - Home: index.md
  # - Blog: blog.md
  # - Projects: projects.md
  - About: about.md
  # - Contact: contact.md
  - Resume: resume.md
site_url: https://vanessaeaton-github-io.pages.dev
theme:
  name: dracula
  custom_dir: overrides
  font:
    text: Poppins

extra_css:
  - stylesheets/extra.css